const virtual_assistant_module = [
    {
        general_bots: [
            {
                keyName: "merge_bubble",
                typeOf: Boolean,
                displayName: "Merge bubble",
                description: "It allows you to gather the various responses in an automation into a single conversation bubble.",
                value: false,
                optionType: "checkbox",
                startSection: true,
                endSection: false,
            },
            {
                keyName: "audio_recognition",
                typeOf: Boolean,
                displayName: "Audio recongnition",
                description: "Allows the bot to understand voice notes.",
                value: false,
                optionType: "checkbox",
                startSection: false,
                endSection: true,
            },
            {
                keyName: "time_options_menu",
                typeOf: Number,
                displayName: "Options menu time",
                description: "Maximum time a user has to give an answer in the Options Menu.",
                value: 0,
                optionType: "time",
                startSection: true,
                endSection: false,
            },
            {
                keyName: "hsm_response_time",
                typeOf: Number,
                displayName: "HSM response time",
                description: "Maximum time a user has to give a response to an Outbound message.",
                value: 0,
                optionType: "time",
                startSection: false,
                endSection: false,
            },
            {
                keyName: "question_time",
                typeOf: Number,
                displayName: "Question times",
                description: "Maximum time a user has to give an answer to a question.",
                value: 0,
                optionType: "time",
                startSection: false,
                endSection: false,
            },
            {
                keyName: "quick_replies_time",
                typeOf: Number,
                displayName: "Quick Response Time (Whatsapp)",
                description: "Maximum time a user has to give a reply to a Whatsapp button or shortcuts.",
                value: 0,
                optionType: "time",
                startSection: false,
                endSection: false,
            },

            {
                keyName: "attempts_number",
                typeOf: Number,
                displayName: "Number of attempts",
                description: "Maximum amount that a user can give an invalid response.",
                value: 0,
                optionType: "number",
                startSection: false,
                endSection: false,
            },
            {
                keyName: "monthly_limit_sessions",
                typeOf: Number,
                displayName: "Limits of sessions per month",
                description: "Maximum number of 24-hour paid sessions a client wishes to have.",
                value: 0,
                optionType: "number",
                startSection: true,
                endSection: false,
            },
        ],
    },
];

export { virtual_assistant_module };
