export const GridIcon = ({ fill = '#00B3C7', stroke = '#fff', width = 22, height = 22 }) => (
  <svg
    fill='none'
    width={width}
    height={height}
    viewBox='0 0 22 22'
    xmlns='http://www.w3.org/2000/svg'
  >
    <rect
      x={0.75}
      y={0.75}
      width={7.3}
      height={7.3}
      rx={1.25}
      fill={fill}
      stroke={stroke}
      strokeWidth={1.5}
    />
    <rect
      x={0.75}
      y={13.95}
      width={7.3}
      height={7.3}
      rx={1.25}
      fill={fill}
      stroke={stroke}
      strokeWidth={1.5}
    />
    <rect
      x={13.95}
      y={0.75}
      width={7.3}
      height={7.3}
      rx={1.25}
      fill={fill}
      stroke={stroke}
      strokeWidth={1.5}
    />
    <rect
      x={13.95}
      y={13.95}
      width={7.3}
      height={7.3}
      rx={1.25}
      fill={fill}
      stroke={stroke}
      strokeWidth={1.5}
    />
  </svg>
)
