import {
    ContainIcon,
    EmptyIcon,
    EndsWithIcon,
    EqualToIcon,
    GraterThanIcon,
    GraterThanOrEqualIcon,
    LessThanOrEqualToIcon,
    NotContainIcon,
    NotEmptyIcon,
    NotEndsWithIcon,
    NotEqualToIcon,
    NotStartsWithIcon,
    RegexIcon,
    RegexMatchIcon,
    RegexNotMatchIcon,
    SmallerThanIcon,
    StartsWithIcon,
} from "@builder/Icons/Operations.Icons";
import { IF_OPERATORS_NAMES } from "@builder/modules/Nodes/If/constants.If-config";

export const IconsByOperator = {
    [IF_OPERATORS_NAMES.CONTAINS]: ContainIcon,
    [IF_OPERATORS_NAMES.NOT_CONTAINS]: NotContainIcon,
    [IF_OPERATORS_NAMES.EQUAL]: EqualToIcon,
    [IF_OPERATORS_NAMES.NOT_EQUAL]: NotEqualToIcon,
    [IF_OPERATORS_NAMES.LARGER]: GraterThanIcon,
    [IF_OPERATORS_NAMES.LARGER_EQUAL]: GraterThanOrEqualIcon,
    [IF_OPERATORS_NAMES.SMALLER]: SmallerThanIcon,
    [IF_OPERATORS_NAMES.SMALLER_EQUAL]: LessThanOrEqualToIcon,
    [IF_OPERATORS_NAMES.STARTS_WITH]: StartsWithIcon,
    [IF_OPERATORS_NAMES.NOT_STARTS_WITH]: NotStartsWithIcon,
    [IF_OPERATORS_NAMES.ENDS_WITH]: EndsWithIcon,
    [IF_OPERATORS_NAMES.NOT_ENDS_WITH]: NotEndsWithIcon,
    [IF_OPERATORS_NAMES.REGEX_MATCH]: RegexMatchIcon,
    [IF_OPERATORS_NAMES.REGEX_NOT_MATCH]: RegexNotMatchIcon,
    [IF_OPERATORS_NAMES.REGEX]: RegexIcon,
    [IF_OPERATORS_NAMES.IS_EMPTY]: EmptyIcon,
    [IF_OPERATORS_NAMES.IS_NOT_EMPTY]: NotEmptyIcon,
};
